### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by micik** [floatinghotpot/cordova-admob-pro#89]
Plugins/com.google.cordova.admob/CDVAdMobPlugin.m:97:8: error: 
      property 'rootViewCon' not found on object of type 'GADBannerView *'
    ad.rootViewCon      troller = [self etViewController];
       ^
1 error generated.

** BUILD FAILED **

**Comment by floatinghotpot** [comment]
The code is: 
```objective-c
ad.rootViewController = [self getViewController];
```

which version of xcode and cordova do you use, and how do you build the code?

**Comment by micik** [comment]
cordova -v 4.1.2
cordova build ios

build on Xcode 6.1.1 -- same problem

plugin:
<gap:plugin name="com.google.cordova.admob" version="2.7.0" source="plugins.cordova.io"/>

**Comment by micik** [comment]
Thank you, saw the problem that the code is interrupted

from
ad.rootViewCon troller = [self etViewController];

to
ad.rootViewController = [self getViewController];

work now
